# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: kube-system
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: null
    CLOUDFLARE_APIKEY: null
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:FUqf6Po=,iv:mrWPZu8lC7gBLkapN9tdPxwxOv32rrbOs3dws82ElpA=,tag:tVEs5IGSc4wGFXgPvc/ylA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcE5VRGNmTEMzTldRNGdr
            YlVnN3BueER2NFdSSGIrUVZnekFpU0xJL0Q4Cm56eWlwYm1KSzNTcy9hVGhmSFRa
            bkxNS3RuV2dPaFQzSWJza2o1SG1xS00KLS0tIGVYc29sRVFBM3JJcGVBbXZHbWh6
            aWNNREJFdU5KK2VmdFF4bHB5U1U3QWsKPlNlghYtnWsLR/qYiRAWnZHL5iLo34wr
            ojrYBX08X5joVnKsWaF/CIC9yicMIuCl/qezKCWEWjwab0LOyjaLVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-09T03:36:36Z"
    mac: ENC[AES256_GCM,data:x6n9TXoYH3iw5tCmapefpzzWqHdd28C3R2LU87Lty7jlwY32i+JbjFGY4+QOa6csV/+7gM6dWP2800tTKbNpuYYsaxxuUjTPGYqGLzPSJcRBTSZXLSQ9YgvxEF1EON3DMFNU5jKoex1KKZTETpEf7Wg7Y0DZFBFfs0FY9bK2nOE=,iv:2Lwy0didvO2v9/rJqvclMTKXU+XAYGW2XMu88AA7x+k=,tag:OL5cEzx376otTT+6hsoRwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
