kind: Secret
ansible_user: ENC[AES256_GCM,data:chFG,iv:v1EDiVIxzWgT4syC3FT1Cy4PRjWFBdPmDz6N01gvoko=,tag:6O6RwUmVBXVUdKBrRQd1Jg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:S94zktP+X5Km6TT0+ciTkA==,iv:1w1kiVb1yx21YxOfB2cGrhnh8N5SnhUBMa3EWPJytHQ=,tag:GcUHLvt/UJAM7DkkAtsHbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc3V5MVpvbVU3dHdXVHdw
            cDg1NnNoRE5lZkNSaDRxMTBmNEJOL0NCb1ZVCkNDUFMvdDRUWUFYRkROclVqdERl
            VHdTbXJ5WWxpMlh5R3hXeVRTTUdGSGMKLS0tIHl6VGljY1pWV1ZleHgxMUt2M3E3
            U09oTlFEeUZUVTQxcUFqamMwdE9aTjgKAgKUvlhX1P3CCI1d4Rw26BiRsVvaRfEL
            wWlzsqBpHJV+eYV2XuQkiITq5ugTDC2IzKCzuNpfNNOW8iMewwmcoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-09T03:36:36Z"
    mac: ENC[AES256_GCM,data:7rguJ66dZvkZeNuunxdK+1som7YNub9Ha5fQd22q4Wjd7Pz7JTZToFY3BnvkztudlQAeTKD/FDw9JRvNFZ1x06F6Eu5z25r339SlmPWRfiHrqFNxeAQtWynKGwKdY7SDXtl9ZGZioRZKbQPdcRfEbher4XtZ29yHDPoR/SmuY6Y=,iv:gCoxcLd89lbAN0I+jRxHXn3a5gBeeUbX6S+22V+27K0=,tag:8P9EIud5H5ywwX04sHicYQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
