kind: Secret
ansible_user: ENC[AES256_GCM,data:7QZ3,iv:nNtKM9j2w10UeYVsZGSfgpvqyec1oLQEd3OnfXAFpmA=,tag:jFKIUXDoVRMxVSgrzPuiFQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Ed3JHfzkLuI45V/dNx685g==,iv:vZAK8LAoBYwbJTECO1ei7Gcun5uvZX7Y2NQy+BNRHQE=,tag:rkIFvfTT6vRg34chal1ElQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOTM4Q2JWSDB0akJ6ajJy
            MVR1Y2pqeXJ6VWR5YlVKSEZ6SjIrWENGeFZNCjVvQVpGNG5kV3FSSWZ3c0hrcWx5
            U29zZWw0bDdTaXpyTEtkeDYxTnV0L3cKLS0tIGFXT1owR0tqT2FUTHlhemYySFBi
            QXJlVzhxVjROOEhPeDJ1Q0dDRUVCeDQKeym62lnABJmcj1Fvz7CMexlQvimkBOt8
            KOrAv3RkIWxmIDqhMVw3S6nEMesxuigAvsJ3UnHoM+Q6d33cNMlWUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-09T03:36:36Z"
    mac: ENC[AES256_GCM,data:vewu0Gi7qmI7TvljSqPTWkD47kGanWwT1ZgAJMLRHWr1IB+rymrLK1JAkrH4sLHfJl/eHpuvhNBCiQZO1wtL/eZitUfmWRLU9oqsFPct1ehpgHcLJjx09AgIL1G/2MZ7tGRHydFqFHkM1NJmpp+nnk2jBilc6emjNKeIj6KBhpE=,iv:HF9Z2UgxQgvSTqDjf17usiJnrirKWTenqOxgUdtV5nY=,tag:wx6eRqea9iV+exsT/SaMDg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
