---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Los_Angeles
  METALLB_LB_RANGE: 192.168.1.10-192-168.1.20
  METALLB_K8S_GATEWAY_ADDR: 192.168.1.11
  METALLB_INGRESS_ADDR: 192.168.1.12
