# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r4m2f92rq9p386jksj2apdxw4xkdug0kvh9pudrj3cdhl5pctffs2r8lff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb0JjOElSMlJqTHU0YVR0
            a2gzcUs4RWVDbjNPR0ZVQmV3R01pT2Y1dFFFCjJHOUxXaGtwS2dvS1hnclJvczZJ
            QW84aGczUm1XbGpBeWphUVY2RWRzN1kKLS0tIFJnaCtteTBac3BpbkdBN09yd0cr
            cGpYZFl1WFhiQlpWelprZHd4WXdET0UKL12Gvmpii9JHwjOI0QhxvTK1ORIMbrAU
            kF9qTcwm6mXdp0VGH8eQYOXOyf0C8bvBeQ6cvHNfQtz1yXaj8xucJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T03:34:07Z"
    mac: ENC[AES256_GCM,data://pbIjkDG/+K7sHtiUgli6Ow8n/OoThkw6hZdFQ9ACqlMlIIPp7FL7OMh5OS4YVEgWcYA/86mHMS8WvIFUljR9+/uJFZI5Ny5svq7L2ZfZ21Nl1pipH7xN9Swq70yYd/K2lS5xRIfIKWCDoOT4Ll0mw8ihbu1CdTNNr7i1jvXqY=,iv:jEM8IIY5+Bs3mQ8zpuNdFXDAE2KSt7g0C18YXBJZY3Q=,tag:uTr5rBXtGmA6TcHNoekLeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
